### ISSUE TITLE
9-Feb Update

### ISSUE THREAD

**Issue by mattbattista** [Hokuten85/XICamera#10]
XICamera is causing windower to crash currently

**Comment by AkadenTK** [comment]
Can confirm, just had crashes logging in this morning. Commented out XICamera from my init script and it loaded the game successfully.
Even loading the addon after being logged in crashes the game though.

**Comment by Hokuten85** [comment]
https://github.com/Hokuten85/XICamera/releases/tag/v0.7.4

KenshiDRK assisted with updated signatures. Hopefully these work better going forward.  Can either of you confirm that this release resolves the issue?

**Comment by kyau** [comment]
Not using Windower but figured I would comment here rather than make another ticket.

Just tried the new `xicamera_ashita4_addon_v0.7.4.zip` on retail using Ashitav4, I am getting an error on load.

![pol_SvPruQLhYQ](https://user-images.githubusercontent.com/470450/218664794-55d0180f-996e-42c1-b7b4-714cbd7b1f7d.png)

**Comment by Hokuten85** [comment]
This usually happens if the addon fails to load the first time. If you have it auto loading, and it initially fails, and then you drop the new version in place and try to load it.  That first signature points to a location in memory that I have to modify so that the camera pan speed scales with the camera distance.  I can try to build something more robust...as it doesn't handle failures very well.

But can you confirm that you get this behavior if you load up a fresh client instance with the new version already in the addon folder?

**Comment by kyau** [comment]
If I leave the addon set to autoload at start in my `default.txt` then POL crashes upon trying to load FFXI and I am directly back to the desktop. Checking the Ashitav4 log file shows that it made it through plugin loading then stopped upon reaching addon loading with no apparent errors in the log however. Once `/addon load xicamera` is removed from `default.txt` FFXI launches just fine again.

In-game without auto-loading I tried to load the addon manually which seems works just fine on a fresh POL instance. I can even use `/cam distance 10` to set the camera back a bit further. However the moment I zone I crash out of FFXI back to the desktop. I even tried to load the addon then unload the addon right before zoning, but I still crashed out of FFXI.

To be thorough I then loaded FFXI without loading the addon at all and zoned a bunch of times to make sure nothing else I was using was causing these issues, without the addon I have zero issues zoning.

**Comment by Hokuten85** [comment]
https://github.com/Hokuten85/XICamera/releases/tag/v0.7.5

fml... can you give this a try? Had to fix some signatures :(

**Comment by kyau** [comment]
Works perfect, no crashes on load and I can zone without issues.

**Comment by Hokuten85** [comment]
thanks for helping to work through the issue. much appreciated.
