### ISSUE TITLE
Signature error after cats eye update

### ISSUE THREAD

**Issue by brad43326** [Hokuten85/XICamera#12]
After client update on catseye today xicamera fails to load.

![CB1FE0C5-49BA-429C-AE69-11A482591256](https://user-images.githubusercontent.com/64338799/218338235-badc115f-f25e-4054-abee-47e90ac23f2a.jpeg)

**Comment by Hokuten85** [comment]
https://github.com/Hokuten85/XICamera/releases/tag/v0.7.4

Can you grab the appropriate release and confirm that it's working for you?

**Comment by Kalani** [comment]
I'm playing on Catseye as well, just grabbed v0.7.4 for Ashita4. Unfortunately, still failing to locate critical signature #1 here.

**Comment by Hokuten85** [comment]
This usually happens if the addon fails to load the first time. If you have it auto loading, and it initially fails, and then you drop the new version in place and try to load it.  That first signature points to a location in memory that I have to modify so that the camera pan speed scales with the camera distance.  I can try to build something more robust...as it doesn't handle failures very well.

But can you confirm that you get this behavior if you load up a fresh client instance with the new version already in the addon folder?

**Comment by Kalani** [comment]
Got it! Starting a fresh client, it does appear to be crashing the entire client if autoloading. Manually loading after logging in on a character does work successfully, however!

**Comment by Hokuten85** [comment]
https://github.com/Hokuten85/XICamera/releases/tag/v0.7.5

fml... can you give this a try? Had to fix some signatures :(

**Comment by brad43326** [comment]
That works!  Even with auto loading, thanks!
