### ISSUE TITLE
not an iusse, just a question

### ISSUE THREAD

**Issue by fgiananti** [Hokuten85/XICamera#2]
Hello, 
sorry to contact you this way, I have a question not related to XICamera but the ffxi camera in general.
In your opinion,  it could be possible to make the 3rd person camera behave like the 1st person one? 
I mean make the 3rd person camera pivot on itself and not on charachter.

**Comment by fgiananti** [comment]
Many thanks!
Alternatively, would using the same method XICamera uses to move the 3rd person camera back, work as well on the on the 1st person one?
By the way, just tried XICamera, very nice, thank you!

**Comment by Hokuten85** [comment]
There's actually stuff built in to the lua implementations to detect 1st person mode, and then disables the camera adjustments. Since focal point is different in 1st person mode, it was having some really weird rotational effects around the focal point. Could probably make it work, but turning the camera gets weird, and the camera chase is also a bit weird.
